name: "Packer"
description: "run packer to build ami"
inputs:
  environment:
    description: "Environment of build"
    required: true
    default: "dev"
  tier:
    description: "Web or api tier"
    required: true
    default: "api"
  application:
    description: "Service or application"
    required: true
  account:
    description: "AWS account id"
    required: true
    default: ""
  vpcId:
    description: "AWS VPC ID"
    required: true
  subnetId:
    description: "subnet id in which the EC2 instance is build in"
    required: true
  securityGroupId:
    description: "security group id used during build"
    required: true

