name: "Run packer script"
description: "run packer to build ami"
inputs:
  environment:
    description: "Environment of build"
    required: true
    default: "dev"
  tier:
    description: "Web or api tier"
    required: true
    default: "api"
  application:
    description: "Service or application"
    required: true
    default: "discovery"
  account:
    description: "AWS account id"
    required: true
  vpcId:
    description: "AWS VPC ID"
    required: true
  subnetId:
    description: "subnet id in which the EC2 instance is build in"
    required: true
  securityGroupId:
    description: "security group id used during build"
    required: true
  run: |
    echo packer build -var "environment={{ input.environment }}" -var "tier={{ input.tier }}" -var "application=discovery-wincore" -var "account={{ input.account" -var "vpcId={{ input.vpcId }}" -var "subnetId={{ input.subnetId }}" -var "securityGroupId={{ input.securityGroupId }}" wincore-2019.json

  shell: bash
