on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install lastest Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
        shell: bash
      - name: Initialise Packer
        run: packer init wincore-2019.pkr.hcl
        shell: bash
      - name: Validate Packer template
        run: packer validate -syntax-only wincore-2019.pkr.hcl
        shell: bash
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: PackerSession
      - name: Create AMI for api
        run: packer build -var="environment=dev" -var="tier=api" -var="application=discovery-wincore" -var="account=825668827209" -var="vpcId=vpc-050fab638f733cdbf" -var="subnetId=subnet-05627bec13d1f7fd1" -var="securityGroupId=sg-0ea4c6933c6061e3b" wincore-2019.pkr.hcl
        shell: bash
        env:
          PACKER_LOG: 1
