on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment - dev, test or live'
        required: true
        default: 'dev'
      tier:
        description: 'Tier - web or api'
        required: true
      account-no:
        description: 'AWS account no.'
        required: true
      vpcId:
        description: 'VPC id'
        required: true
      subnetId:
        description: 'Subnet id'
        required: true
      securityGroupId:
        description: 'Security group id'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # validate the packer template
      -name: Validate packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: wincore-2019.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-on-error=abort -var environment=dev -var tier=api -var application=discovery-wincore -var account=825668827209 -var vpcId=vpc-050fab638f733cdbf -var subnetId=subnet-05627bec13d1f7fd1 -var securityGroupId=sg-0ea4c6933c6061e3b"
          target: wincore-2019.pkr.hcl
        env:
          PACKER_LOG: 1
