on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment - dev, test or live'
        required: true
        default: 'dev'
      tier:
        description: 'Tier - web or api'
        required: true
      account-no:
        description: 'AWS account no.'
        required: true
      vpcId:
        description: 'VPC id'
        required: true
      subnetId:
        description: 'Subnet id'
        required: true
      securityGroupId:
        description: 'Security group id'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use lastest Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
        shell: bash
      - name: Create AMI
        run: |
          packer validate \
            -var="environment=${{ github.event.inputs.environment }}" /
            -var="tier=${{ github.event.inputs.tier }}" /
            -var="application=discovery-wincore" /
            -var="account=825668827209" /
            -var="vpcId=vpc-050fab638f733cdbf" /
            -var="subnetId=subnet-05627bec13d1f7fd1" /
            -var="securityGroupId=sg-0ea4c6933c6061e3b" /
            wincore-2019.pkr.hcl

