on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "curl packer"
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        shell: bash
      - name: "add repo"
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        shell: bash
      - name: "install packer"
        run: sudo apt-get update && sudo apt-get install packer
        shell: bash
      - uses: ./.github/actions/packer
