on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment - dev, test or live'
        required: true
        default: 'dev'
      tier:
        description: 'Tier - web or api'
        required: true
      account-no:
        description: 'AWS account no.'
        required: true
      vpcId:
        description: 'VPC id'
        required: true
      subnetId:
        description: 'Subnet id'
        required: true
      securityGroupId:
        description: 'Security group id'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install lastest Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
        shell: bash
      - name: Where am I?
        run: ls -alh
        shell: bash
      - name: Initialise Packer
        run: packer init wincore-2019.pkr.hcl
        shell: bash
      - name: Validate Packer template
        run: packer validate -syntax-only wincore-2019.pkr.hcl
        shell: bash
      - name: Create AMI
        run: |
          packer build /
            -var="environment=dev" /
            -var="tier=api" /
            -var="application=discovery-wincore" /
            -var="account=825668827209" /
            -var="vpcId=vpc-050fab638f733cdbf" /
            -var="subnetId=subnet-05627bec13d1f7fd1" /
            -var="securityGroupId=sg-0ea4c6933c6061e3b" /
            wincore-2019.pkr.hcl
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ROLE_EXTERNAL_ID: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PACKER_LOG: 1
