on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use lastest Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Build AMI
        uses: riznob/packer-build-action@v1.5
        with:
          templateFile: 'wincore-2019.pkr.hcl'
          varFile: 'variables.pkrvars.hcl'
          workingDir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
